### ISSUE TITLE
404  npm install @hardiknaik/react-number-scroll 报404

### ISSUE THREAD

**Issue by yummyo** [mehardiknaik/react-number-scroll#2]
是不是npm仓库删了，怎么git有仓库，npm下载报404

**Comment by mehardiknaik** [comment]
This library is deprecated please find https://github.com/mehardiknaik/react-animate-number this one

**Comment by mehardiknaik** [comment]
This library is deprecated please find https://github.com/mehardiknaik/react-animate-number this one
